hangman_frontend/src/main/java/com/francisco/hangaman/front/model/HangmanChallengeWord.java
package com.francisco.hangaman.front.model;

import java.io.Serializable;

public class HangmanChallengeWord implements Serializable
{
    public void setChallengeWord(String challengeWord)
    {
        this.challengeWord = challengeWord;
    }

    public HangmanChallengeWord(String challengeWord)
    {
        this.challengeWord = challengeWord;
    }

    public HangmanChallengeWord()
    {

    }

    public String getChallengeWord() {
        return challengeWord;
    }

    private String challengeWord;


}

hangman_frontend/src/main/java/com/francisco/hangaman/front/controller/HangmanController.java
package com.francisco.hangaman.front.controller;

import com.francisco.hangaman.front.service.HangmanService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.util.ArrayList;
import java.util.List;

@Component
@ManagedBean
@SessionScoped
public class HangmanController
{

    @Autowired
    private HangmanService hangmanService;

    private int mistakes = 0;

    private String challegeWord;
    private List<String> letters = new ArrayList<String>();

    public void onInitializeGame()
    {
        challegeWord = hangmanService.getChallengeWord();
        letters.clear();
        mistakes = 0;
    }

    public boolean isGameInitialized()
    {
        return challegeWord != null;
    }

    public boolean isGameCompleted()
    {
        if (challegeWord == null || letters.isEmpty())
        {
            return false;
        }

        for (int i = 0; i < challegeWord.length(); i++)
        {
            if (!letters.contains(challegeWord.substring(i, i + 1)))
            {
                return false;
            }
        }

        return true;
    }

    public String getMaskedWord()
    {
        if (challegeWord == null)
        {
            return "";
        }

        if (letters.isEmpty())
        {
            return generateMask(challegeWord);
        }

        // get the positions of letters we already know
        final List<Integer> positions = new ArrayList<>();

        for (int i = 0; i < challegeWord.length(); i++)
        {
            for (final String letter : letters)
            {
                if (challegeWord.charAt(i) == letter.toUpperCase().charAt(0))
                {
                    positions.add(i);
                }
            }
        }

        // generate mask with new known letter
        final StringBuilder sb = new StringBuilder();

        for (int i = 0; i < challegeWord.length(); i++)
        {
            boolean hasUpdateChar = false;

            for (final Integer position : positions)
            {
                if (i == position)
                {
                    sb.append(challegeWord.charAt(i)).append(" ");
                    hasUpdateChar = true;
                }
            }

            if (!hasUpdateChar)
            {
                sb.append("_ ");
            }
        }
        return sb.toString().trim();
    }

    public String getLastEnteredLetter()
    {
        return "";
    }

    public void setLastEnteredLetter(final String lastEnteredLetter)
    {
        if ( lastEnteredLetter != null && lastEnteredLetter.trim().length() > 0 )
        {
            final String letter = lastEnteredLetter.substring( lastEnteredLetter.length() - 1).toUpperCase();

            int pos = challegeWord.indexOf(letter);

            if (pos == -1)
            {
                mistakes ++;
            }

            if ( ! letters.contains(letter) )
            {
                letters.add(letter);
            }
        }
    }

    public int getMistakes()
    {
        return mistakes;
    }

    private static String generateMask(final String word)
    {
        final StringBuilder sb = new StringBuilder();

        for (int i = 0; i < word.length(); i++)
        {
            sb.append("_ ");
        }
        return sb.toString().trim();
    }
}

hangman_frontend/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">

<h:head>
    <title>HangMan Game by Francisco Anizio</title>
</h:head>

<h:body style="max-width: 50%; margin: auto; padding: 25px;">

    <h:form id="form">

        <p:graphicImage value="images/hangman0.gif" library="demo " rendered="#{hangmanController.mistakes eq '0' }" />
        <p:graphicImage value="images/hangman1.gif" library="demo " rendered="#{hangmanController.mistakes eq '1' }" />
        <p:graphicImage value="images/hangman2.gif" library="demo " rendered="#{hangmanController.mistakes eq '2' }" />
        <p:graphicImage value="images/hangman3.gif" library="demo " rendered="#{hangmanController.mistakes eq '3' }" />
        <p:graphicImage value="images/hangman4.gif" library="demo " rendered="#{hangmanController.mistakes eq '4' }" />
        <p:graphicImage value="images/hangman5.gif" library="demo " rendered="#{hangmanController.mistakes eq '5' }" />
        <p:graphicImage value="images/hangman6.gif" library="demo " rendered="#{hangmanController.mistakes eq '6' }" />
        <p:graphicImage value="images/hangman7.gif" library="demo " rendered="#{hangmanController.mistakes eq '7' }" />
        <p:graphicImage value="images/hangman8.gif" library="demo " rendered="#{hangmanController.mistakes eq '8' }" />


            <br/>

            <p:commandButton value="Start Game" rendered="#{hangmanController.mistakes eq '0' }" >
                <p:ajax event="click" update="form" listener="#{hangmanController.onInitializeGame}" />
            </p:commandButton>

            <p:commandButton value="Reset Game" rendered="#{hangmanController.mistakes gt 0 }" >
                <p:ajax event="click" update="form" listener="#{hangmanController.onInitializeGame}" />
            </p:commandButton>

            <br/>
            <br/>
            <br/>

            <div>
                <h:outputText id="maskedWord" value="#{hangmanController.maskedWord}" />
            </div>

            <br/>

            <h:outputText
                    rendered="#{hangmanController.gameCompleted}"
                    escape="false"
                    style="display: block; color: green; text-align: center; padding: 20px;"
                    value="Congrats, you guess the word &lt;strong&gt;#{hangmanController.getMaskedWord()}&lt;/strong&gt;"
            />

            <p:panel header="Play now!" rendered="#{not hangmanController.gameCompleted and hangmanController.gameInitialized and hangmanController.mistakes lt 8 }" style="margin-top: 10px;">
                <h:outputText value="Try typing a letter: " />
                <p:inputText value="#{hangmanController.lastEnteredLetter}"  >
                    <p:ajax event="keyup" update="form" />
                </p:inputText>
            </p:panel>

            <br/>
            <br/>

            You have <h:outputText value="#{hangmanController.mistakes}" /> mistakes !




    </h:form>

</h:body>
</html>